service: auth-server # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs10.x
functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get